using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PrReviewAgent;

internal static class Program
{
    private const string AnthropicVersion = "2023-06-01";
    private const string Model = "claude-sonnet-4-20250514";
    private const int MaxDiffChars = 150_000;
    private static readonly TimeSpan HttpTimeout = TimeSpan.FromMinutes(5);

    public static async Task<int> Main(string[] args)
    {
        var options = Options.FromEnvironment();
        if (options.AnthropicApiKey is null or "")
        {
            await Console.Error.WriteLineAsync("::error::Set ANTHROPIC_API_KEY (Anthropic API key).");
            return 1;
        }

        string systemPrompt;
        try
        {
            systemPrompt = await ReviewRules.LoadSystemPromptAsync(CancellationToken.None);
        }
        catch (Exception ex)
        {
            await Console.Error.WriteLineAsync("::error::" + ex.Message);
            return 1;
        }

        string diff;
        if (!string.IsNullOrWhiteSpace(options.DiffFile))
        {
            diff = await File.ReadAllTextAsync(options.DiffFile);
        }
        else
        {
            if (options.GitHubToken is null or "" || options.Repository is null || options.PrNumber is null)
            {
                await Console.Error.WriteLineAsync(
                    "::error::Provide DIFF_FILE, or GITHUB_TOKEN + GITHUB_REPOSITORY + PR_NUMBER to fetch the diff.");
                return 1;
            }

            diff = await GitHub.FetchPullRequestDiffAsync(
                options.GitHubToken,
                options.Repository,
                options.PrNumber.Value,
                CancellationToken.None);
        }

        var truncated = false;
        if (diff.Length > MaxDiffChars)
        {
            diff = diff[..MaxDiffChars]
                   + "\n\n[… diff truncated at "
                   + MaxDiffChars
                   + " characters for API limits …]";
            truncated = true;
        }

        var userContent = new StringBuilder()
            .AppendLine("Review this pull request unified diff. Focus on changed lines and immediate context.")
            .AppendLine()
            .AppendLine("```diff")
            .AppendLine(diff)
            .AppendLine("```");

        if (truncated)
            userContent.AppendLine().AppendLine("_Note: The diff was truncated for size; review may miss later files._");

        string reviewText;
        try
        {
            reviewText = await Anthropic.CompleteReviewAsync(
                options.AnthropicApiKey,
                systemPrompt,
                userContent.ToString(),
                CancellationToken.None);
        }
        catch (HttpRequestException ex)
        {
            await Console.Error.WriteLineAsync($"::error::Anthropic API error: {ex.Message}");
            return 1;
        }

        if (string.IsNullOrWhiteSpace(reviewText))
        {
            await Console.Error.WriteLineAsync("::error::Empty response from Claude.");
            return 1;
        }

        var blockMerge = RequiresBlockMerge(reviewText);
        if (blockMerge)
        {
            await Console.Error.WriteLineAsync(
                "::error::BLOCK_MERGE: true — review reported hardcoded secrets or a critical security vulnerability. Fix before merging.");
        }

        var body = new StringBuilder()
            .AppendLine("## Automated review (Claude Sonnet)")
            .AppendLine()
            .AppendLine(reviewText.Trim())
            .AppendLine()
            .AppendLine("---")
            .AppendLine("*Generated by GitHub Actions from `.cursor/rules/code-review-agent.mdc`.*")
            .ToString();

        if (options.DryRun)
        {
            Console.WriteLine(body);
            return blockMerge ? 1 : 0;
        }

        if (options.GitHubToken is null or "" || options.Repository is null || options.PrNumber is null)
        {
            await Console.Error.WriteLineAsync("::error::Posting requires GITHUB_TOKEN, GITHUB_REPOSITORY, and PR_NUMBER.");
            return 1;
        }

        try
        {
            await GitHub.CreateIssueCommentAsync(
                options.GitHubToken,
                options.Repository,
                options.PrNumber.Value,
                body,
                CancellationToken.None);
        }
        catch (HttpRequestException ex)
        {
            await Console.Error.WriteLineAsync($"::error::GitHub API error: {ex.Message}");
            return 1;
        }

        return blockMerge ? 1 : 0;
    }

    private sealed record Options(
        string? AnthropicApiKey,
        string? GitHubToken,
        string? Repository,
        int? PrNumber,
        string? DiffFile,
        bool DryRun)
    {
        public static Options FromEnvironment()
        {
            var token = Environment.GetEnvironmentVariable("GITHUB_TOKEN")
                        ?? Environment.GetEnvironmentVariable("GH_TOKEN");
            var repo = Environment.GetEnvironmentVariable("GITHUB_REPOSITORY")?.Trim();
            int? pr = null;
            var prRaw = Environment.GetEnvironmentVariable("PR_NUMBER")?.Trim();
            if (int.TryParse(prRaw, out var prParsed))
                pr = prParsed;

            var diffFile = Environment.GetEnvironmentVariable("DIFF_FILE")?.Trim();
            if (string.IsNullOrEmpty(diffFile))
                diffFile = null;

            var dryRun = string.Equals(Environment.GetEnvironmentVariable("DRY_RUN"), "1", StringComparison.Ordinal);

            return new Options(
                Environment.GetEnvironmentVariable("ANTHROPIC_API_KEY")?.Trim(),
                string.IsNullOrEmpty(token) ? null : token,
                string.IsNullOrEmpty(repo) ? null : repo,
                pr,
                diffFile,
                dryRun);
        }
    }

    private static class GitHub
    {
        public static async Task<string> FetchPullRequestDiffAsync(
            string token,
            string ownerSlashRepo,
            int pullNumber,
            CancellationToken ct)
        {
            var (owner, repo) = ParseRepository(ownerSlashRepo);
            using var client = CreateClient(token);
            var url = $"https://api.github.com/repos/{owner}/{repo}/pulls/{pullNumber}";
            using var request = new HttpRequestMessage(HttpMethod.Get, url);
            request.Headers.Accept.ParseAdd("application/vnd.github.v3.diff");
            using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);
            response.EnsureSuccessStatusCode();
            return await response.Content.ReadAsStringAsync(ct);
        }

        public static async Task CreateIssueCommentAsync(
            string token,
            string ownerSlashRepo,
            int issueNumber,
            string body,
            CancellationToken ct)
        {
            var (owner, repo) = ParseRepository(ownerSlashRepo);
            using var client = CreateClient(token);
            var url = $"https://api.github.com/repos/{owner}/{repo}/issues/{issueNumber}/comments";
            var payload = JsonSerializer.Serialize(new CreateCommentBody(body));
            using var content = new StringContent(payload, Encoding.UTF8, "application/json");
            using var response = await client.PostAsync(url, content, ct);
            response.EnsureSuccessStatusCode();
        }

        private static HttpClient CreateClient(string token)
        {
            var client = new HttpClient { Timeout = HttpTimeout };
            client.DefaultRequestHeaders.UserAgent.ParseAdd("PerryHomesTracker-PrReviewAgent/1.0");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            return client;
        }

        private static (string Owner, string Repo) ParseRepository(string ownerSlashRepo)
        {
            var parts = ownerSlashRepo.Split('/', 2, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length != 2)
                throw new ArgumentException("GITHUB_REPOSITORY must be 'owner/repo'.", nameof(ownerSlashRepo));
            return (parts[0], parts[1]);
        }
    }

    private sealed record CreateCommentBody([property: JsonPropertyName("body")] string Body);

    /// <summary>Parses Claude's review for <c>BLOCK_MERGE: true</c> (case-insensitive). Any matching line fails CI.</summary>
    private static bool RequiresBlockMerge(string reviewText)
    {
        foreach (var line in reviewText.ReplaceLineEndings("\n").Split('\n'))
        {
            var trimmed = line.Trim();
            if (!trimmed.StartsWith("BLOCK_MERGE", StringComparison.OrdinalIgnoreCase))
                continue;

            var colon = trimmed.IndexOf(':');
            if (colon < 0)
                continue;

            var key = trimmed[..colon].Trim();
            if (!key.Equals("BLOCK_MERGE", StringComparison.OrdinalIgnoreCase))
                continue;

            var value = trimmed[(colon + 1)..].Trim();
            if (value.Equals("true", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    private static class Anthropic
    {
        public static async Task<string> CompleteReviewAsync(string apiKey, string systemPrompt, string userContent, CancellationToken ct)
        {
            using var client = new HttpClient { Timeout = HttpTimeout };
            using var request = new HttpRequestMessage(HttpMethod.Post, "https://api.anthropic.com/v1/messages");
            request.Headers.Add("x-api-key", apiKey);
            request.Headers.Add("anthropic-version", AnthropicVersion);
            var body = new AnthropicRequest(Model, 8192, systemPrompt, [new Message("user", userContent)]);
            request.Content = new StringContent(
                JsonSerializer.Serialize(body),
                Encoding.UTF8,
                "application/json");

            using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, ct);
            if (!response.IsSuccessStatusCode)
            {
                var err = await response.Content.ReadAsStringAsync(ct);
                throw new HttpRequestException($"Anthropic HTTP {(int)response.StatusCode}: {err}");
            }

            await using var stream = await response.Content.ReadAsStreamAsync(ct);
            var doc = await JsonDocument.ParseAsync(stream, cancellationToken: ct);
            return ExtractText(doc.RootElement);
        }

        private static string ExtractText(JsonElement root)
        {
            if (!root.TryGetProperty("content", out var content) || content.ValueKind != JsonValueKind.Array)
                return "";

            var sb = new StringBuilder();
            foreach (var block in content.EnumerateArray())
            {
                if (block.TryGetProperty("type", out var type) && type.GetString() == "text"
                    && block.TryGetProperty("text", out var text))
                    sb.AppendLine(text.GetString());
            }

            return sb.ToString().Trim();
        }
    }

    private sealed record AnthropicRequest(
        [property: JsonPropertyName("model")] string Model,
        [property: JsonPropertyName("max_tokens")] int MaxTokens,
        [property: JsonPropertyName("system")] string System,
        [property: JsonPropertyName("messages")] Message[] Messages);

    private sealed record Message(
        [property: JsonPropertyName("role")] string Role,
        [property: JsonPropertyName("content")] string Content);

}
